name: report
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.74
  - coreutils=8.25
  - pip=19.3.1
  - python=3.7.4
  - snakemake-minimal
  - pandoc=2.2.3.2
  - pip:
    - git+https://github.com/cov-ert/clusterfunk.git
    - matplotlib==3.2.1
    - numpy==1.18.1
    - pweave==0.30.3
    - scipy==1.4.1
    - tabulate==0.8.7
    - pandas==1.0.1
    - scipy==1.4.1
    - requests==2.20.0
    - epiweeks==2.1.1
    - argparse==1.4.0
    - geopandas==0.7.0
    - shapely==1.7.0
    - descartes==1.1.0
    
    

